# Generated by Django 5.0.7 on 2024-08-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questionattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='questionAttempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionsAttempt', to='quiz.quizattempt'),
        ),
    ]
